name: CI WEB Docker VPS

on:
  workflow_call:
    inputs:
      NVM_VERSION:
        required: true
        type: string
      DOCKER_IMAGE_PREFIX:
        required: true
        type: string
      SERVICES:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
        
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: "Login to Docker Hub"
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        env:
            DOCKER_IMAGE_PREFIX: ${{ env.DOCKER_IMAGE_PREFIX }}
  
      - name: Check out code
        uses: actions/checkout@v2
            
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.NVM_VERSION }}

      - name: Install dependencies
        run: |
            npm install -g @angular/cli
            npm install
            
      - name: Build Angular project
        run: |
            ng build --configuration production

      - name: Build Docker image
        run: |
            for i in $(seq 1 $(echo ${{ env.SERVICES }} | wc -w)); do
                service=$(echo ${{ env.SERVICES }} | cut -d ' ' -f $i)
                echo "Building and pushing $service ...."

                docker build -t ${{ env.DOCKER_IMAGE_PREFIX }}:$service . || exit 1

                docker push ${{ env.DOCKER_IMAGE_PREFIX }}:$service
            done
        env:
            DOCKER_IMAGE_PREFIX: ${{ env.DOCKER_IMAGE_PREFIX }}
            SERVICES: ${{ env.SERVICES }}
  