name: CI API Docker VPS

on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        required: true
        type: string
      DOCKER_IMAGE_PREFIX:
        required: true
        type: string
      SERVICES:
        required: true
        type: string
      PORTS:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
     
jobs:
  ci:
    uses: VitorHeser/templates-pipelines/.github/workflows/ci-api-docker-vps-template.yml@main
    with:
      JAVA_VERSION: ${{ inputs.DOCKER_IMAGE_PREFIX }}
      DOCKER_IMAGE_PREFIX: ${{ inputs.DOCKER_IMAGE_PREFIX }}
      SERVICES: ${{ inputs.SERVICES }}
      PORTS: ${{ inputs.PORTS }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  cd:
    needs: ci
    uses: VitorHeser/templates-pipelines/.github/workflows/cd-docker-vps-template.yml@main
    with:
      DOCKER_IMAGE_PREFIX: ${{ inputs.DOCKER_IMAGE_PREFIX }}
      SERVICES: ${{ inputs.SERVICES }}
      PORTS: ${{ inputs.PORTS }}
      PORTSOUT: ${{ inputs.PORTS }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}